"""BERTScore for real human-reference rehabilitation reports only.

The input files are generated by ``src.llm.generate``.  Rows without an
Excel-traceable reference are rejected rather than silently treated as
synthetic references.
"""
from __future__ import annotations

import argparse
import csv
import glob
import json
import re
from collections import defaultdict
from pathlib import Path
from statistics import mean, stdev
from typing import Dict, List, Tuple


ENCODER = "hfl/chinese-roberta-wwm-ext"
NUM_LAYERS = 8
_FOLD_RE = re.compile(r"fold(\d+)_test\.json$")


def _device() -> str:
    import torch
    return "cuda" if torch.cuda.is_available() else "cpu"


def _score(rows: List[Dict[str, object]], device: str, batch_size: int) -> List[Tuple[str, float, float, float]]:
    usable = [row for row in rows if row.get("has_human_reference") and str(row.get("ref", "")).strip()]
    if not usable:
        raise ValueError("No rows with traceable human references in prediction file.")
    from bert_score import score as bertscore
    precision, recall, f1 = bertscore(
        cands=[str(row["hyp"]) for row in usable],
        refs=[str(row["ref"]) for row in usable],
        model_type=ENCODER,
        num_layers=NUM_LAYERS,
        lang="zh",
        rescale_with_baseline=False,
        batch_size=batch_size,
        device=device,
        verbose=False,
    )
    return [
        (str(row["subject_id"]), float(p), float(r), float(f))
        for row, p, r, f in zip(usable, precision.tolist(), recall.tolist(), f1.tolist())
    ]


def _mean_std(values: List[float]) -> Tuple[float, float]:
    return (mean(values), stdev(values) if len(values) > 1 else 0.0)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pred-glob", default="results/llm/predictions/*/fold*_test.json")
    parser.add_argument("--out-dir", type=Path, default=Path("results/llm/evaluation/bertscore"))
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--device", default=None)
    args = parser.parse_args()

    paths = [Path(value) for value in sorted(glob.glob(args.pred_glob))]
    if not paths:
        raise SystemExit(f"No prediction files matched: {args.pred_glob}")
    device = args.device or _device()
    summaries: Dict[str, List[Tuple[float, float, float]]] = defaultdict(list)
    for path in paths:
        match = _FOLD_RE.search(path.name)
        if not match:
            continue
        model_id, fold = path.parent.name, int(match.group(1))
        rows = json.loads(path.read_text(encoding="utf-8"))
        scores = _score(rows, device=device, batch_size=args.batch_size)
        out_path = args.out_dir / model_id / f"bertscore_fold{fold}.csv"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(["subject_id", "source", "bertscore_p", "bertscore_r", "bertscore_f1"])
            for sid, p, r, f in scores:
                writer.writerow([sid, "real_human_rehab_text", f"{p:.6f}", f"{r:.6f}", f"{f:.6f}"])
        summaries[model_id].append(tuple(mean(value[index] for value in scores) for index in (1, 2, 3)))
        print(f"[bertscore] {model_id} fold={fold}; n={len(scores)} -> {out_path}")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    with (args.out_dir / "bertscore_mean.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["model_id", "reference_scope", "n_folds", "P_mean", "P_std", "R_mean", "R_std", "F1_mean", "F1_std"])
        for model_id, fold_scores in sorted(summaries.items()):
            p, p_std = _mean_std([score[0] for score in fold_scores])
            r, r_std = _mean_std([score[1] for score in fold_scores])
            f, f_std = _mean_std([score[2] for score in fold_scores])
            writer.writerow([model_id, "real_human_rehab_text", len(fold_scores), f"{p:.6f}", f"{p_std:.6f}", f"{r:.6f}", f"{r_std:.6f}", f"{f:.6f}", f"{f_std:.6f}"])


if __name__ == "__main__":
    main()
